// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import "@openzeppelin/contracts/token/ERC721/ERC721.sol";
import "@openzeppelin/contracts/access/Ownable.sol";
import "./interfaces/IVerifier.sol";

/**
 * @title MerchantRegistry
 * @dev A simple ZKID KYC registry for the HashBazaar marketplace.
 * Users submit a Groth16 proof showing they know the secret to a valid KYC commitment.
 * Once verified, they are minted a non-transferable (soulbound) Merchant NFT.
 */
contract MerchantRegistry is ERC721, Ownable {
    // The ZK Snark Verifier contract generated by snarkjs
    IVerifier public immutable verifier;

    // Mapping to store nullifier hashes to prevent double-minting
    mapping(uint256 => bool) public isNullifierUsed;

    // Mapping to store authorized KYC commitments (issued by HashKey off-chain)
    mapping(uint256 => bool) public isValidCommitment;

    uint256 private _nextTokenId;

    // Events
    event MerchantVerified(address indexed merchant, uint256 indexed tokenId, uint256 nullifierHash);
    event CommitmentAdded(uint256 indexed commitment);

    constructor(address _verifier) ERC721("HashKey Merchant ZKID", "HMZKID") Ownable(msg.sender) {
        verifier = IVerifier(_verifier);
    }

    /**
     * @dev Add valid KYC commitments issued by HashKey's KYC infrastructure.
     * Only the owner (admin) can add valid commitments.
     */
    function addValidCommitment(uint256 commitment) external onlyOwner {
        isValidCommitment[commitment] = true;
        emit CommitmentAdded(commitment);
    }

    /**
     * @dev Submit a ZK proof to verify KYC and mint a Merchant NFT.
     * @param a Proof A (from snarkjs)
     * @param b Proof B (from snarkjs)
     * @param c Proof C (from snarkjs)
     * @param input Public inputs [nullifierHash, commitment]
     */
    function verifyAndMint(
        uint256[2] memory a,
        uint256[2][2] memory b,
        uint256[2] memory c,
        uint256[2] memory input
    ) external {
        // In circom, input[0] is typically the first output (nullifierHash)
        // input[1] is the public input (commitment)
        uint256 nullifierHash = input[0];
        uint256 commitment = input[1];

        // 1. Ensure the commitment was issued by HashKey and is valid
        require(isValidCommitment[commitment], "Invalid or unknown KYC commitment");

        // 2. Ensure this nullifier hash hasn't been used yet (sybil resistance)
        require(!isNullifierUsed[nullifierHash], "KYC credential already used");

        // 3. Verify the Groth16 proof
        bool isValidProof = verifier.verifyProof(a, b, c, input);
        require(isValidProof, "Invalid ZK proof");

        // 4. Mark nullifier as used
        isNullifierUsed[nullifierHash] = true;

        // 5. Mint the Soulbound Merchant Token to the sender
        uint256 tokenId = _nextTokenId++;
        _mint(msg.sender, tokenId);

        emit MerchantVerified(msg.sender, tokenId, nullifierHash);
    }

    /**
     * @dev Overrides ERC721 transfer logic to make the token soulbound (non-transferable).
     * Only minting (from == address(0)) or burning (to == address(0)) is allowed.
     */
    function _update(address to, uint256 tokenId, address auth) internal override returns (address) {
        address from = _ownerOf(tokenId);
        require(from == address(0) || to == address(0), "Soulbound token: transfer not allowed");
        return super._update(to, tokenId, auth);
    }
}